AWSTemplateFormatVersion: 2010-09-09
Description: Redis cluster in Elasticache
Parameters:
  CacheNodeType:
    Type: String
    Description: Cache Node Type
    Default: cache.t2.micro
  VpcId:
    Description: The VPC ID
    Type: AWS::EC2::VPC::Id
    Default: vpc-49f76f20

Resources:
  TrafficContainerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: redis replication group access

  SubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: subnet group for Redis cluster
      SubnetIds: !Split
        - ","
        - Fn::ImportValue:
            !Sub ${VpcId}:data-subnet:ids

  RedisSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: redis replication group access
      VpcId: !Ref VpcId
      SecurityGroupIngress: 
        - FromPort: 6379
          ToPort: 6379
          IpProtocol: tcp
          SourceSecurityGroupId: !Ref TrafficContainerSecurityGroup

  ReplicationGroup:
    Type: AWS::ElastiCache::ReplicationGroup
    Properties:
      CacheNodeType: !Ref CacheNodeType
      CacheSubnetGroupName: !Ref SubnetGroup
      Engine: redis
      EngineVersion: 3.2.4
      NumNodeGroups: 2
      ReplicasPerNodeGroup: 1
      ReplicationGroupDescription: Redis cluster
      SecurityGroupIds: [ !Ref RedisSecurityGroup ]

Outputs:
  RedisReplicationGroup:
    Description: Redis Replication Group
    Value: !Ref ReplicationGroup
  TrafficContainerSecurityGroup:
    Description: Security group for accessing Redis cluster
    Value: !Ref TrafficContainerSecurityGroup
    Export:
      Name: !Sub ${VpcId}:redis-traffic-container-sg
